# Generated by Django 5.0.1 on 2024-02-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsitioweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vconferencia',
            old_name='horafinal',
            new_name='horaFinal',
        ),
        migrations.RenameField(
            model_name='vconferencia',
            old_name='horainic',
            new_name='horaInicio',
        ),
        migrations.RemoveField(
            model_name='vconferencia',
            name='fechfinal',
        ),
        migrations.AddField(
            model_name='vconferencia',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsitioweb.departamento'),
        ),
        migrations.AddField(
            model_name='vconferencia',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsitioweb.sala'),
        ),
        migrations.AddField(
            model_name='vconferencia',
            name='tipoconf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsitioweb.tipoconf'),
        ),
    ]
